[package]
authors.workspace    = true
categories.workspace = true
description          = "Utilities to deserialize values"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_deserialize"
repository.workspace = true
version              = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_console     = { workspace = true }
biome_diagnostics = { workspace = true }
biome_json_parser = { workspace = true }
biome_json_syntax = { workspace = true }
biome_rowan       = { workspace = true }
bitflags          = { workspace = true }
indexmap          = { workspace = true, features = ["serde"] }
schemars          = { workspace = true, optional = true }
serde             = { workspace = true }
serde_json        = { workspace = true }
tracing           = { workspace = true }

[features]
schema = ["schemars", "schemars/indexmap"]
