[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's Glimmer template parser"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_glimmer_parser"
publish              = true
repository.workspace = true
version              = "0.0.1"

[lints]
workspace = true

[dependencies]
biome_console         = { workspace = true }
biome_diagnostics     = { workspace = true }
biome_glimmer_factory = { path = "../biome_glimmer_factory" }
biome_glimmer_syntax  = { path = "../biome_glimmer_syntax" }
biome_parser          = { workspace = true }
biome_rowan           = { workspace = true }
biome_unicode_table   = { workspace = true }
tracing               = { workspace = true }

[dev-dependencies]
biome_test_utils  = { workspace = true }
insta             = { workspace = true }
quickcheck        = { workspace = true }
quickcheck_macros = { workspace = true }
tests_macros      = { path = "../tests_macros" }

[target.'cfg(target_os = "windows")'.dev-dependencies]
mimalloc = { workspace = true }

[target.'cfg(all(target_family="unix", not(all(target_arch = "aarch64", target_env = "musl"))))'.dev-dependencies]
tikv-jemallocator = { workspace = true }
