[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's YAML formatter"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_yaml_formatter"
publish              = true
repository.workspace = true
version              = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_deserialize = { workspace = true }
biome_diagnostics = { workspace = true }
biome_formatter   = { workspace = true }
biome_rowan       = { workspace = true }
biome_suppression = { workspace = true }
biome_yaml_syntax = { workspace = true }
schemars          = { workspace = true, optional = true }
serde             = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
biome_formatter      = { workspace = true, features = ["countme"] }
biome_formatter_test = { path = "../biome_formatter_test" }
biome_fs             = { path = "../biome_fs" }
biome_parser         = { path = "../biome_parser" }
biome_service        = { path = "../biome_service" }
biome_yaml_parser    = { path = "../biome_yaml_parser" }
camino               = { workspace = true }
countme              = { workspace = true, features = ["enable"] }
tests_macros         = { path = "../tests_macros" }

# cargo-workspaces metadata
[package.metadata.workspaces]
independent = true

[features]
schema = ["dep:schemars", "serde"]
serde  = ["dep:serde"]

[lints]
workspace = true
