[package]
authors     = { workspace = true }
description = "Rome suppression utilities"
edition     = { workspace = true }
license     = { workspace = true }
name        = "biome_suppression"
repository  = { workspace = true }
version     = "0.2.0"


[dependencies]
biome_diagnostics = { workspace = true }
biome_console      = { workspace = true }
rome_rowan        = { workspace = true }
