[package]
edition = "2021"
name    = "biome_migrate"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_analyze     = { workspace = true }
biome_diagnostics = { workspace = true }
biome_rowan       = { workspace = true }
lazy_static       = { workspace = true }
biome_json_syntax  = { workspace = true }

[dev-dependencies]
rome_json_parser = { workspace = true }
