[package]
name                 = "biome_js_type_info_macros"
version              = "0.0.1"
authors.workspace    = true
edition.workspace    = true
description          = "Macros to help implement type resolution"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[lib]
proc-macro = true

[dependencies]
proc-macro-error2 = { workspace = true }
proc-macro2       = { workspace = true }
quote             = { workspace = true }
syn               = { workspace = true, features = ["extra-traits"] }

[lints]
workspace = true
