[package]
name                 = "biome_project_layout"
version              = "0.0.1"
authors.workspace    = true
edition.workspace    = true
description          = "Data structure for tracking projects and their packages"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[dependencies]
biome_package = { workspace = true }
biome_parser  = { workspace = true }
biome_rowan   = { workspace = true }
camino        = { workspace = true }
papaya        = { workspace = true }
rustc-hash    = { workspace = true }

[lints]
workspace = true
