[package]
authors.workspace    = true
categories.workspace = true
description          = "Utilities to treat text sizes/ranges in a more type-safe"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_text_size"
repository.workspace = true
version              = "0.5.7"

[dependencies]
schemars = { workspace = true, optional = true }
serde    = { workspace = true, optional = true }

[features]
schema = ["dep:schemars", "serde"]
serde  = ["dep:serde"]

[dev-dependencies]
serde_test        = "1.0.177"
static_assertions = "1.1"

[[test]]
name              = "serde"
path              = "tests/serde.rs"
required-features = ["serde"]

[lints]
workspace = true
