[package]
authors.workspace    = true
categories.workspace = true
description          = "Workspace project handler"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_project"
publish              = false
repository.workspace = true
version              = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_console            = { workspace = true }
biome_deserialize        = { workspace = true }
biome_deserialize_macros = { workspace = true }
biome_diagnostics        = { workspace = true }
biome_json_syntax        = { workspace = true }
biome_parser             = { workspace = true }
biome_rowan              = { workspace = true }
biome_text_size          = { workspace = true }
node-semver              = "2.1.0"
rustc-hash               = { workspace = true }
serde                    = { workspace = true }

[dev-dependencies]
biome_json_parser = { path = "../biome_json_parser" }
insta             = { workspace = true }
tests_macros      = { path = "../tests_macros" }

[lints]
workspace = true
