[package]
authors.workspace    = true
categories.workspace = true
description          = "Utilities to create JSON AST for biome_json_parser"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_json_factory"
repository.workspace = true
version              = "0.5.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_json_syntax = { workspace = true }
biome_rowan       = { workspace = true }

[lints]
workspace = true
