[package]
name                 = "biome_json_factory"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "Utilities to create JSON AST for biome_json_parser"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_json_syntax = { workspace = true }
biome_rowan       = { workspace = true }

[lints]
workspace = true
