[package]
name                 = "biome_html_factory"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "Utilities to create HTML AST for biome_html_parser"
documentation        = "https://docs.rs/biome_html_factory"
repository.workspace = true
license.workspace    = true
publish              = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_html_syntax = { workspace = true }
biome_rowan       = { workspace = true }

[lints]
workspace = true
