[package]
authors.workspace    = true
categories.workspace = true
description          = "Factory functions for creating Glimmer AST nodes"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_glimmer_factory"
publish              = true
repository.workspace = true
version              = "0.0.1"

[lints]
workspace = true

[dependencies]
biome_glimmer_syntax = { workspace = true }
biome_rowan          = { workspace = true, features = ["serde"] }
