[package]
authors.workspace    = true
description          = "Utilities to create Glimmer AST for biome_glimmer_parser"
documentation        = "https://docs.rs/biome_glimmer_factory"
edition.workspace    = true
license.workspace    = true
name                 = "biome_glimmer_factory"
publish              = true
repository.workspace = true
version              = "0.5.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_glimmer_syntax = { workspace = true }
biome_rowan          = { workspace = true }

[lints]
workspace = true
