[package]
authors.workspace    = true
categories.workspace = true
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "tests_macros"
publish              = false
repository.workspace = true
version              = "0.0.0"

[lib]
proc-macro = true

[dependencies]
biome_string_case = { workspace = true }
case              = "1.0.0"
globwalk          = "0.9.1"
proc-macro-error2 = { workspace = true }
proc-macro2       = { workspace = true }
quote             = "1.0.14"
syn               = "2.0.59"
