[package]
authors.workspace    = true
categories.workspace = true
description          = "Workspace package handler"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_package"
publish              = true
repository.workspace = true
version              = "0.5.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_console            = { workspace = true }
biome_deserialize        = { workspace = true, features = ["camino", "indexmap"] }
biome_deserialize_macros = { workspace = true }
biome_diagnostics        = { workspace = true }
biome_json_parser        = { workspace = true }
biome_json_syntax        = { workspace = true }
biome_json_value         = { workspace = true, features = ["oxc_resolver"] }
biome_parser             = { workspace = true }
biome_rowan              = { workspace = true }
biome_text_size          = { workspace = true }
camino                   = { workspace = true }
indexmap                 = { workspace = true }
node-semver              = "2.1.0"
oxc_resolver             = { workspace = true }
rustc-hash               = { workspace = true }
serde                    = { workspace = true }
static_assertions        = "1.1.0"

[dev-dependencies]
insta        = { workspace = true }
tests_macros = { path = "../tests_macros" }

[lints]
workspace = true
