[package]
authors.workspace    = true
categories.workspace = true
description          = "A small wrapper around std::path::PathBuf contains additional information and convenient methods"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_fs"
repository.workspace = true
version              = "0.5.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_diagnostics = { workspace = true }
crossbeam         = { workspace = true }
directories       = "5.0.1"
indexmap          = { workspace = true }
oxc_resolver      = { workspace = true }
parking_lot       = { version = "0.12.1", features = ["arc_lock"] }
rayon             = { workspace = true }
rustc-hash        = { workspace = true }
schemars          = { workspace = true, optional = true }
serde             = { workspace = true }
tracing           = { workspace = true }

[features]
serde = ["schemars", "biome_diagnostics/schema"]

[lints]
workspace = true
