[package]
authors.workspace    = true
categories.workspace = true
description          = "A small wrapper around std::path::PathBuf contains additional information and convenient methods"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_fs"
repository.workspace = true
version              = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_console     = { workspace = true }
biome_diagnostics = { workspace = true }
crossbeam         = "0.8.2"
indexmap          = { workspace = true }
parking_lot       = { version = "0.12.0", features = ["arc_lock"] }
rayon             = "1.7.0"
schemars          = { workspace = true, optional = true }
serde             = { workspace = true, features = ["derive"], optional = true }
tracing           = { workspace = true }

[features]
serde = ["dep:serde", "schemars", "biome_diagnostics/schema"]
