[package]
name                 = "biome_fs"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "A small wrapper around std::path::PathBuf contains additional information and convenient methods"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_diagnostics = { workspace = true, features = ["std"] }
camino            = { workspace = true }
crossbeam         = { workspace = true }
directories       = { workspace = true }
enumflags2        = { workspace = true, features = ["serde"] }
papaya            = { workspace = true }
parking_lot       = { version = "0.12.5", features = ["arc_lock"] }
path-absolutize   = { workspace = true }
rayon             = { workspace = true }
rustc-hash        = { workspace = true }
schemars          = { workspace = true, optional = true }
serde             = { workspace = true }
smallvec          = { workspace = true }
tracing           = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[features]
schema = ["biome_diagnostics/schema", "dep:schemars", "serde"]
serde  = ["camino/serde1"]

[lints]
workspace = true
