[package]
name                 = "biome_tailwind_factory"
version              = "0.0.1"
authors.workspace    = true
edition.workspace    = true
description          = "Utilities to create Tailwind AST for biome_tailwind_factory"
documentation        = "https://docs.rs/biome_tailwind_factory"
repository.workspace = true
license.workspace    = true
publish              = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_rowan           = { workspace = true }
biome_tailwind_syntax = { workspace = true }

[lints]
workspace = true
