[package]
name                 = "biome_string_case"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "Utilities to convert string cases"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[dependencies]
biome_rowan = { workspace = true, optional = true }
caseless    = "0.2.2"

[features]
biome_rowan = ["dep:biome_rowan"]

[lints]
workspace = true
