[package]
name                 = "biome_graphql_parser"
version              = "0.1.0"
authors.workspace    = true
edition.workspace    = true
description          = "Biome's GraphQL parser"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
harness = false
name    = "graphql_parser"

[dependencies]
biome_console         = { workspace = true }
biome_diagnostics     = { workspace = true }
biome_graphql_factory = { workspace = true }
biome_graphql_syntax  = { workspace = true }
biome_parser          = { workspace = true }
biome_rowan           = { workspace = true }
biome_unicode_table   = { workspace = true }
tracing               = { workspace = true }
unicode-bom           = { workspace = true }

[dev-dependencies]
biome_test_utils  = { workspace = true }
criterion         = { package = "codspeed-criterion-compat", version = "*" }
insta             = { workspace = true }
quickcheck        = { workspace = true }
quickcheck_macros = { workspace = true }
tests_macros      = { workspace = true }

[target.'cfg(all(target_family="unix", not(all(target_arch = "aarch64", target_env = "musl"))))'.dev-dependencies]
tikv-jemallocator = { workspace = true }

[target.'cfg(target_os = "windows")'.dev-dependencies]
mimalloc = { workspace = true }

[lints]
workspace = true
