[package]
name                 = "biome_ruledoc_utils"
version              = "0.0.1"
authors.workspace    = true
edition.workspace    = true
description          = "Utilities for running code blocks in rule docs"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true

[dependencies]
anyhow               = { workspace = true }
biome_analyze        = { workspace = true }
biome_configuration  = { workspace = true }
biome_fs             = { workspace = true }
biome_js_analyze     = { workspace = true }
biome_js_parser      = { workspace = true }
biome_json_parser    = { workspace = true }
biome_module_graph   = { workspace = true }
biome_project_layout = { workspace = true }
biome_service        = { workspace = true }
biome_test_utils     = { workspace = true }
camino               = { workspace = true }

[lints]
workspace = true
