blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation issues
    url: https://github.com/biomejs/website
    about: File an issue in the website repository
  - name: ğŸ§© VSCode extension issues
    url: https://github.com/biomejs/biome-vscode
    about: File an issue in the biome-vscode repository
  - name: ğŸ§© IntelliJ extension issues
    url: https://github.com/biomejs/biome-intellij
    about: File an issue in the biome-intellij repository
  - name: âœ… Linter rule requests
    url: https://github.com/biomejs/biome/discussions/3
    about: Please add a comment to the discussion named "Linter rules from other sources"
  - name: ğŸ’¡ Feature requests
    url: https://github.com/biomejs/biome/discussions/new
    about: Please use a new Github discussion to propose ideas of feature requests
  - name: ğŸ—£ï¸ Chat
    url: https://biomejs.dev/chat
    about: Our Discord server is active and is used for real-time discussions including contribution collaboration, questions, and more!
  - name: ğŸ¤” Support
    url: https://biomejs.dev/chat
    about: "This issue tracker is not for support questions. Visit our community Discord and the #support channel for assistance!"
  - name: ğŸ†˜ Code of Conduct Reports
    url: https://github.com/biomejs/biome/blob/main/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct
    about: Please use the contact information in Code of Conduct as issues created here are public
