[package]
name                 = "biome_ungrammar"
version              = "0.3.1"
authors.workspace    = true
edition.workspace    = true
description          = "A DSL for describing concrete syntax trees"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = false

[lints]
workspace = true
