[package]
name                 = "biome_line_index"
version              = "0.1.0"
authors.workspace    = true
edition.workspace    = true
description          = "Biome's tools for converting between byte offsets and line / column positions"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_text_size = { workspace = true }
rustc-hash      = { workspace = true }

[lints]
workspace = true
