[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's command line interface"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_cli"
publish              = false
repository.workspace = true
version              = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "biome"
path = "src/main.rs"

[dependencies]
anyhow                   = "1.0.52"
biome_analyze            = { workspace = true }
biome_console            = { workspace = true }
biome_deserialize        = { workspace = true }
biome_deserialize_macros = { workspace = true }
biome_diagnostics        = { workspace = true }
biome_flags              = { workspace = true }
biome_formatter          = { workspace = true }
biome_fs                 = { workspace = true }
biome_js_formatter       = { workspace = true }
biome_json_formatter     = { workspace = true }
biome_json_parser        = { workspace = true }
biome_json_syntax        = { workspace = true }
biome_lsp                = { workspace = true }
biome_migrate            = { workspace = true }
biome_rowan              = { workspace = true }
biome_service            = { workspace = true }
biome_text_edit          = { workspace = true }
biome_text_size          = { workspace = true }
bpaf                     = { workspace = true, features = ["bright-color"] }
crossbeam                = "0.8.1"
dashmap                  = { workspace = true }
hdrhistogram             = { version = "7.5.0", default-features = false }
indexmap                 = { workspace = true }
lazy_static              = { workspace = true }
rayon                    = "1.5.1"
rustc-hash               = { workspace = true }
serde                    = { workspace = true, features = ["derive"] }
serde_json               = { workspace = true }
tokio                    = { workspace = true, features = ["io-std", "io-util", "net", "time", "rt", "sync", "rt-multi-thread", "macros"] }
tracing                  = { workspace = true }
tracing-appender         = "0.2"
tracing-subscriber       = { version = "0.3.16", features = ["env-filter", "json"] }
tracing-tree             = "0.2.2"

[target.'cfg(unix)'.dependencies]
libc  = "0.2.127"
tokio = { workspace = true, features = ["process"] }

[target.'cfg(windows)'.dependencies]
mimalloc = "0.1.29"

[target.'cfg(all(target_family="unix", not(all(target_arch = "aarch64", target_env = "musl"))))'.dependencies]
tikv-jemallocator = "0.5.0"

[dev-dependencies]
biome_css_formatter  = { workspace = true }
biome_js_formatter   = { workspace = true }
biome_json_formatter = { workspace = true }
biome_json_parser    = { workspace = true }
insta                = { workspace = true }
tokio                = { workspace = true, features = ["io-util"] }

[features]
docgen = ["bpaf/docgen"]

[lints]
workspace = true
