[package]
authors.workspace    = true
categories.workspace = true
description          = "Macros to write text using a HTML-like syntax"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_markup"
repository.workspace = true
version              = "0.4.0"


[lib]
proc-macro = true

[dependencies]
proc-macro-error = { version = "1.0.4", default-features = false }
proc-macro2      = "1.0.63"
quote            = "1.0.14"

[lints]
workspace = true
