[package]
name                 = "biome_markup"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "Macros to write text using a HTML-like syntax"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[lib]
proc-macro = true

[dependencies]
proc-macro-error2 = { workspace = true }
proc-macro2       = { workspace = true }
quote             = "1.0.14"

[lints]
workspace = true
