[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's JavaScript linter"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_js_analyze"
repository.workspace = true
version              = "0.4.0"

[dependencies]
biome_analyze            = { workspace = true }
biome_aria               = { workspace = true }
biome_console            = { workspace = true }
biome_control_flow       = { workspace = true }
biome_deserialize        = { workspace = true }
biome_deserialize_macros = { workspace = true }
biome_diagnostics        = { workspace = true }
biome_js_factory         = { workspace = true }
biome_js_semantic        = { workspace = true }
biome_js_syntax          = { workspace = true }
biome_json_factory       = { workspace = true }
biome_json_syntax        = { workspace = true }
biome_rowan              = { workspace = true }
biome_unicode_table      = { workspace = true }
lazy_static              = { workspace = true }
log                      = "0.4.20"
natord                   = "1.0.9"
roaring                  = "0.10.1"
rustc-hash               = { workspace = true }
schemars                 = { workspace = true, optional = true }
serde                    = { workspace = true, features = ["derive"] }
serde_json               = { workspace = true }
smallvec                 = { workspace = true }

[dev-dependencies]
biome_js_parser  = { path = "../biome_js_parser", features = ["tests"] }
biome_test_utils = { path = "../biome_test_utils" }
biome_text_edit  = { path = "../biome_text_edit" }
countme          = { workspace = true, features = ["enable"] }
insta            = { workspace = true, features = ["glob"] }
tests_macros     = { path = "../tests_macros" }

[features]
schema = ["schemars", "biome_deserialize/schema"]

[lints]
workspace = true
