[package]
name                 = "biome_glob"
version              = "0.1.0"
authors.workspace    = true
edition.workspace    = true
description          = "<DESCRIPTION>"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[dependencies]
biome_deserialize        = { workspace = true, optional = true }
biome_deserialize_macros = { workspace = true, optional = true }
biome_text_size          = { workspace = true, optional = true }
globset                  = { workspace = true }
schemars                 = { workspace = true, optional = true }
serde                    = { workspace = true, optional = true }

[features]
biome_deserialize = ["dep:biome_deserialize", "dep:biome_deserialize_macros", "dep:biome_text_size"]
schema            = ["dep:schemars", "serde"]
serde             = ["dep:serde"]

[lints]
workspace = true
