[package]
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
name                 = "rome_js_transform"
repository.workspace = true
version              = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_analyze     = { workspace = true }
biome_diagnostics = { workspace = true }
lazy_static       = { workspace = true }
biome_console      = { workspace = true }
rome_js_factory   = { workspace = true }
rome_js_syntax    = { workspace = true }
rome_rowan        = { workspace = true }


[dev-dependencies]
biome_analyze     = { workspace = true }
biome_test_utils  = { workspace = true }
insta             = { workspace = true }
rome_js_formatter = { workspace = true }
rome_js_parser    = { workspace = true }
tests_macros      = { workspace = true }
