[package]
name                 = "biome_grit_patterns"
version              = "0.0.1"
authors.workspace    = true
edition.workspace    = true
description          = "Biome implementation for Grit Patterns"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = false

[[bench]]
harness = false
name    = "grit_query"

[dependencies]
biome_analyze        = { workspace = true }
biome_console        = { workspace = true }
biome_css_parser     = { workspace = true }
biome_css_syntax     = { workspace = true }
biome_diagnostics    = { workspace = true }
biome_grit_parser    = { workspace = true }
biome_grit_syntax    = { workspace = true }
biome_js_parser      = { workspace = true }
biome_js_syntax      = { workspace = true }
biome_json_parser    = { workspace = true }
biome_json_syntax    = { workspace = true }
biome_parser         = { workspace = true }
biome_rowan          = { workspace = true }
biome_string_case    = { workspace = true }
camino               = { workspace = true }
grit-pattern-matcher = { workspace = true }
grit-util            = { workspace = true }
path-absolutize      = { version = "3.1.1", features = ["use_unix_paths_on_wasm"], optional = false }
rand                 = { version = "=0.8.5" }
regex                = { workspace = true }
rustc-hash           = { workspace = true }
schemars             = { workspace = true, optional = true }
serde                = { workspace = true, features = ["derive"], optional = true }
serde_json           = { workspace = true, optional = true }

[dev-dependencies]
biome_test_utils = { path = "../biome_test_utils" }
criterion        = { package = "codspeed-criterion-compat", version = "*" }
insta            = { workspace = true }
tests_macros     = { path = "../tests_macros" }

[target.'cfg(all(target_family="unix", not(all(target_arch = "aarch64", target_env = "musl"))))'.dev-dependencies]
tikv-jemallocator = { workspace = true }

[target.'cfg(target_os = "windows")'.dev-dependencies]
mimalloc = { workspace = true }

[features]
schema = ["biome_js_parser/schema", "dep:schemars", "serde"]
serde  = ["dep:serde", "dep:serde_json"]

[lints]
workspace = true
