[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome implementing for matching Grit Patterns"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_grit_patterns"
publish              = false
repository.workspace = true
version              = "0.0.1"

[dependencies]
anyhow               = { workspace = true }
biome_console        = { workspace = true }
biome_diagnostics    = { workspace = true }
biome_grit_parser    = { workspace = true }
biome_grit_syntax    = { workspace = true }
biome_js_parser      = { workspace = true }
biome_js_syntax      = { workspace = true }
biome_parser         = { workspace = true }
biome_rowan          = { workspace = true }
grit-pattern-matcher = { version = "0.3" }
grit-util            = { version = "0.3" }
im                   = { version = "15.1.0" }
path-absolutize      = { version = "3.1.1", optional = false, features = ["use_unix_paths_on_wasm"] }
rand                 = { version = "0.8" }
regex                = { workspace = true }
rustc-hash           = { workspace = true }
serde                = { workspace = true, features = ["derive"] }

[dev-dependencies]
biome_test_utils = { path = "../biome_test_utils" }
insta            = { workspace = true }
tests_macros     = { path = "../tests_macros" }

[lints]
workspace = true
