[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome implementing for matching Grit Patterns"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_grit_patterns"
publish              = false
repository.workspace = true
version              = "0.0.1"

[dependencies]
biome_console     = { workspace = true }
biome_diagnostics = { workspace = true }
biome_grit_parser = { workspace = true }
biome_parser      = { workspace = true }
#marzano-core      = { git = "https://github.com/getgrit/gritql.git", optional = true }
serde = { workspace = true, features = ["derive"] }

[features]
default = [] # add "grit" to enable linking to Grit's Marzano engine
#grit    = ["dep:marzano-core"]

[lints]
workspace = true
