[package]
authors.workspace    = true
categories.workspace = true
description          = "Utilities for tests"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_test_utils"
publish              = false
repository.workspace = true
version              = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_rgb             = "0.2.0"
biome_analyze        = { workspace = true }
biome_configuration  = { workspace = true }
biome_console        = { workspace = true }
biome_deserialize    = { workspace = true }
biome_diagnostics    = { workspace = true }
biome_formatter      = { workspace = true }
biome_fs             = { workspace = true }
biome_js_analyze     = { workspace = true }
biome_js_parser      = { workspace = true }
biome_js_type_info   = { workspace = true }
biome_json_parser    = { workspace = true }
biome_module_graph   = { workspace = true }
biome_package        = { workspace = true }
biome_project_layout = { workspace = true }
biome_rowan          = { workspace = true, features = ["countme"] }
biome_service        = { workspace = true }
biome_string_case    = { workspace = true }
camino               = { workspace = true }
countme              = { workspace = true, features = ["enable"] }
json_comments        = "0.2.2"
serde_json           = { workspace = true }
similar              = { workspace = true }
ureq                 = { workspace = true }
url                  = { workspace = true }


[lints]
workspace = true
