[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's JSON linter"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_json_analyze"
repository.workspace = true
version              = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_analyze     = { workspace = true }
biome_console     = { workspace = true }
biome_diagnostics = { workspace = true }
biome_json_syntax = { workspace = true }
biome_rowan       = { workspace = true }
lazy_static       = { workspace = true }
rustc-hash        = { workspace = true }

[dev-dependencies]
biome_json_factory = { path = "../biome_json_factory" }
biome_json_parser  = { path = "../biome_json_parser" }
biome_service      = { path = "../biome_service" }
biome_test_utils   = { path = "../biome_test_utils" }
insta              = { workspace = true, features = ["glob"] }
tests_macros       = { path = "../tests_macros" }

[lints]
workspace = true
