[package]
name                 = "biome_json_analyze"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "Biome's JSON linter"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
harness = false
name    = "json_analyzer"

[dependencies]
biome_analyze        = { workspace = true }
biome_analyze_macros = { workspace = true }
biome_console        = { workspace = true }
biome_diagnostics    = { workspace = true }
biome_json_factory   = { workspace = true }
biome_json_syntax    = { workspace = true }
biome_rowan          = { workspace = true }
biome_rule_options   = { workspace = true }
biome_string_case    = { workspace = true }
biome_suppression    = { workspace = true }
camino               = { workspace = true }
rustc-hash           = { workspace = true }

[dev-dependencies]
biome_configuration = { workspace = true }
biome_json_parser   = { path = "../biome_json_parser" }
biome_test_utils    = { path = "../biome_test_utils" }
criterion           = { package = "codspeed-criterion-compat", version = "*" }
insta               = { workspace = true, features = ["glob"] }
tests_macros        = { path = "../tests_macros" }

[build-dependencies]
filetime = { workspace = true }

[target.'cfg(all(target_family="unix", not(all(target_arch = "aarch64", target_env = "musl"))))'.dev-dependencies]
tikv-jemallocator = { workspace = true }

[target.'cfg(target_os = "windows")'.dev-dependencies]
mimalloc = { workspace = true }

[lints]
workspace = true
