[package]
name = "biome_glimmer_syntax"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
description = "SyntaxKind and common rowan definitions for biome_glimmer_parser"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish = true
repository.workspace = true

[dependencies]
biome_rowan       = { workspace = true, features = ["serde"] }
biome_string_case = { workspace = true }
schemars          = { workspace = true, optional = true }
serde             = { workspace = true, features = ["derive"] }

[dev-dependencies]

[features]
schema = ["schemars", "biome_rowan/serde"]

[lints]
workspace = true
