[package]
authors.workspace    = true
categories.workspace = true
description          = "SyntaxKind and common rowan definitions for biome_glimmer_parser"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_glimmer_syntax"
publish              = true
repository.workspace = true
version              = "0.5.7"

[dependencies]
biome_rowan = { workspace = true, features = ["serde"] }
schemars    = { workspace = true, optional = true }
serde       = { workspace = true, features = ["derive"] }

[dev-dependencies]
# TODO: Add when these crates are created
# biome_glimmer_factory = { path = "../biome_glimmer_factory" }
# biome_glimmer_parser  = { path = "../biome_glimmer_parser" }

[features]
schema = ["schemars", "biome_rowan/serde"]

[lints]
workspace = true
