[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's language server protocol"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_lsp"
publish              = false
repository.workspace = true
version              = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow              = { workspace = true }
biome_analyze       = { workspace = true }
biome_configuration = { workspace = true }
biome_console       = { workspace = true }
biome_deserialize   = { workspace = true }
biome_diagnostics   = { workspace = true }
biome_fs            = { workspace = true }
biome_rowan         = { workspace = true }
biome_service       = { workspace = true }
biome_text_edit     = { workspace = true }
futures             = "0.3.31"
rustc-hash          = { workspace = true }
serde               = { workspace = true, features = ["derive"] }
serde_json          = { workspace = true }
tokio               = { workspace = true, features = ["rt", "io-std"] }
tower-lsp           = { version = "0.20.0" }
tracing             = { workspace = true, features = ["attributes"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
tower = { version = "0.4.13", features = ["timeout"] }

[lints]
workspace = true
