[package]
name                 = "biome_lsp"
version              = "0.0.0"
authors.workspace    = true
edition.workspace    = true
description          = "Biome's language server protocol"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow               = { workspace = true }
biome_analyze        = { workspace = true }
biome_configuration  = { workspace = true }
biome_console        = { workspace = true }
biome_deserialize    = { workspace = true }
biome_diagnostics    = { workspace = true }
biome_fs             = { workspace = true }
biome_line_index     = { workspace = true }
biome_lsp_converters = { workspace = true }
biome_resolver       = { workspace = true }
biome_rowan          = { workspace = true }
biome_service        = { workspace = true }
biome_text_edit      = { workspace = true }
camino               = { workspace = true }
crossbeam            = { workspace = true }
futures              = "0.3.31"
papaya               = { workspace = true }
rustc-hash           = { workspace = true }
serde                = { workspace = true, features = ["derive"] }
serde_json           = { workspace = true }
tokio                = { workspace = true, features = ["io-std", "rt"] }
tower-lsp-server     = { workspace = true }
tracing              = { workspace = true, features = ["attributes"] }
uuid                 = { workspace = true, features = ["v4"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
tower = { workspace = true, features = ["timeout"] }

[lints]
workspace = true
