[package]
authors.workspace    = true
categories.workspace = true
description          = "Responsible for resolving dependency path"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_resolver"
publish              = false
repository.workspace = true
version              = "0.1.0"

[lints]
workspace = true

[dependencies]
biome_console     = { workspace = true }
biome_diagnostics = { workspace = true }
biome_fs          = { workspace = true }
biome_json_value  = { workspace = true }
biome_package     = { workspace = true }
biome_rowan       = { workspace = true }
camino            = { workspace = true }
