[package]
name                 = "biome_resolver"
version              = "0.1.0"
authors.workspace    = true
edition.workspace    = true
description          = "Responsible for resolving dependency path"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = false

[dependencies]
biome_console     = { workspace = true }
biome_diagnostics = { workspace = true }
biome_fs          = { workspace = true }
biome_json_value  = { workspace = true }
biome_package     = { workspace = true }
biome_rowan       = { workspace = true }
camino            = { workspace = true }

[lints]
workspace = true
