[package]
name                 = "biome_json_value"
version              = "0.1.0"
authors.workspace    = true
edition.workspace    = true
description          = "Mutable JSON values constructable from biome_json_syntax"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[dependencies]
biome_deserialize        = { workspace = true, features = ["indexmap"] }
biome_deserialize_macros = { workspace = true }
biome_json_syntax        = { workspace = true }
biome_rowan              = { workspace = true }
indexmap                 = { workspace = true }
rustc-hash               = { workspace = true }
static_assertions        = { workspace = true }

[dev-dependencies]
biome_json_parser = { workspace = true }

[lints]
workspace = true
