[package]
authors.workspace    = true
categories.workspace = true
description          = "SyntaxKind and common rowan definitions for biome_grit_parser"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_grit_syntax"
repository.workspace = true
version              = "0.5.7"

[dependencies]
biome_rowan       = { workspace = true, features = ["serde"] }
biome_string_case = { workspace = true }
camino            = { workspace = true }
schemars          = { workspace = true, optional = true }
serde             = { workspace = true, features = ["derive"] }

[features]
schema = ["schemars", "biome_rowan/serde"]


[lints]
workspace = true
