[package]
authors.workspace    = true
categories.workspace = true
description          = "SyntaxKind and common rowan definitions for biome_grit_parser"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_grit_syntax"
repository.workspace = true
version              = "0.5.7"

[dependencies]
biome_rowan = { workspace = true }
schemars    = { version = "0.8.16", optional = true }
serde       = { version = "1.0.197", features = ["derive"], optional = true }

[features]
serde = ["dep:serde", "schemars", "biome_rowan/serde"]

[lints]
workspace = true
