[package]
description = "Internal script to make sure that the metadata or the rules are correct"
edition     = "2021"
name        = "rules_check"
publish     = false
version     = "0.0.0"

[dependencies]
anyhow                = { workspace = true }
biome_analyze         = { workspace = true }
biome_console         = { workspace = true }
biome_css_analyze     = { workspace = true }
biome_css_parser      = { workspace = true }
biome_css_syntax      = { workspace = true }
biome_diagnostics     = { workspace = true }
biome_graphql_analyze = { workspace = true }
biome_graphql_parser  = { workspace = true }
biome_graphql_syntax  = { workspace = true }
biome_js_analyze      = { workspace = true }
biome_js_parser       = { workspace = true }
biome_js_syntax       = { workspace = true }
biome_json_analyze    = { workspace = true }
biome_json_parser     = { workspace = true }
biome_json_syntax     = { workspace = true }
biome_service         = { workspace = true }
pulldown-cmark        = "0.12.2"


[lints]
workspace = true
