[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's YAML parser"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_yaml_parser"
repository.workspace = true
version              = "0.0.1"

[lints]
workspace = true

[dependencies]
biome_console       = { workspace = true }
biome_diagnostics   = { workspace = true }
biome_parser        = { workspace = true }
biome_rowan         = { workspace = true }
biome_unicode_table = { workspace = true }
biome_yaml_syntax   = { workspace = true }
tracing             = { workspace = true }


[dev-dependencies]
quickcheck        = { workspace = true }
quickcheck_macros = { workspace = true }
