[package]
name                 = "biome_syntax_codegen"
version              = "0.1.0"
authors.workspace    = true
edition.workspace    = true
description          = "Biome utility to codegen a grammar for the parser"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = false

[[example]]
name = "minigrammar"

[dependencies]
anyhow            = { workspace = true }
biome_string_case = { workspace = true }
biome_ungrammar   = { workspace = true }
proc-macro2       = { workspace = true, features = ["span-locations"] }
quote             = { workspace = true }

[lints]
workspace = true
