[package]
name                 = "biome_json_parser"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "Biome's JSON parser"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

# cargo-workspaces metadata
[package.metadata.workspaces]
independent = true

[[bench]]
harness = false
name    = "json_parser"

[dependencies]
biome_console       = { workspace = true }
biome_diagnostics   = { workspace = true }
biome_json_factory  = { workspace = true }
biome_json_syntax   = { workspace = true }
biome_parser        = { workspace = true }
biome_rowan         = { workspace = true }
biome_unicode_table = { workspace = true }
tracing             = { workspace = true }
unicode-bom         = { workspace = true }

[dev-dependencies]
biome_test_utils  = { workspace = true }
criterion         = { package = "codspeed-criterion-compat", version = "*" }
insta             = { workspace = true }
quickcheck        = { workspace = true }
quickcheck_macros = { workspace = true }
tests_macros      = { path = "../tests_macros" }

[target.'cfg(all(target_family="unix", not(all(target_arch = "aarch64", target_env = "musl"))))'.dev-dependencies]
tikv-jemallocator = { workspace = true }

[target.'cfg(target_os = "windows")'.dev-dependencies]
mimalloc = { workspace = true }

[lints]
workspace = true
