[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's JSON parser"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_json_parser"
repository.workspace = true
version              = "0.5.7"

[dependencies]
biome_console       = { workspace = true }
biome_diagnostics   = { workspace = true }
biome_json_factory  = { workspace = true }
biome_json_syntax   = { workspace = true }
biome_parser        = { workspace = true }
biome_rowan         = { workspace = true }
biome_unicode_table = { workspace = true }
tracing             = { workspace = true }
unicode-bom         = { workspace = true }

[dev-dependencies]
insta             = { workspace = true }
quickcheck        = { workspace = true }
quickcheck_macros = { workspace = true }
tests_macros      = { path = "../tests_macros" }

# cargo-workspaces metadata
[package.metadata.workspaces]
independent = true

[lints]
workspace = true
