[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's JSON parser"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_json_parser"
repository.workspace = true
version              = "0.1.0"

[dependencies]
biome_console          = { workspace = true }
biome_diagnostics      = { workspace = true }
biome_js_unicode_table = { workspace = true }
biome_json_factory     = { workspace = true }
biome_json_syntax      = { workspace = true }
biome_parser           = { workspace = true }
biome_rowan            = { workspace = true }
tracing                = { workspace = true }
unicode-bom = "2.0.3"

[dev-dependencies]
insta             = { workspace = true }
quickcheck        = { workspace = true }
quickcheck_macros = { workspace = true }
tests_macros      = { path = "../tests_macros" }

# cargo-workspaces metadata
[package.metadata.workspaces]
independent = true
