[package]
authors     = ["Biome Developers and Contributors"]
categories  = ["development-tools", "web-programming"]
description = "WebAssembly bindings to the Biome workspace API"
edition     = "2024"
homepage    = "https://biomejs.dev/"
keywords    = ["formatter", "linter", "parser", "wasm"]
license     = "MIT OR Apache-2.0"
name        = "biome_wasm"
publish     = false
repository  = "https://github.com/biomejs/biome"
version     = "1.9.4"

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
biome_console            = { workspace = true }
biome_diagnostics        = { workspace = true }
biome_fs                 = { workspace = true }
biome_service            = { workspace = true, features = ["schema"] }
camino                   = { workspace = true }
# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys                   = "0.3.83"
serde                    = { workspace = true }
serde_json               = { workspace = true }
serde-wasm-bindgen       = "0.6.5"
# IMPORTANT: if you update this package, you must update justfile and workflows so we install the same CLI version
wasm-bindgen             = { version = "0.2.106", features = ["serde-serialize"] }

[build-dependencies]
biome_js_factory   = { workspace = true }
biome_js_formatter = { workspace = true }
biome_rowan        = { workspace = true }
biome_service      = { workspace = true, features = ["schema"] }
quote              = "1.0.14"
schemars           = { workspace = true }

[features]
default = ["console_error_panic_hook"]

[lints]
workspace = true
