[package]
authors     = ["Biome Developers and Contributors"]
categories  = ["development-tools", "web-programming"]
description = "WebAssembly bindings to the Biome workspace API"
edition     = "2021"
homepage    = "https://biomejs.dev/"
keywords    = ["parser", "linter", "formatter", "wasm"]
license     = "MIT OR Apache-2.0"
name        = "biome_wasm"
publish     = false
repository  = "https://github.com/biomejs/biome"
version     = "1.7.3"


[lib]
crate-type = ["cdylib", "rlib"]

[features]
default           = ["console_error_panic_hook"]
experimental-grit = ["biome_service/experimental-grit"]
experimental-html = ["biome_service/experimental-html"]

[dependencies]
biome_console      = { workspace = true }
biome_diagnostics  = { workspace = true }
biome_service      = { workspace = true }
js-sys             = "0.3.72"
serde              = { workspace = true }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen       = { version = "0.2.95", features = ["serde-serialize"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }


[build-dependencies]
biome_js_factory   = { workspace = true }
biome_js_formatter = { workspace = true }
biome_rowan        = { workspace = true }
biome_service      = { workspace = true, features = ["schema"] }
quote              = "1.0.14"

[lints]
workspace = true

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false
