[package]
name                 = "biome_graphql_factory"
version              = "0.1.0"
authors.workspace    = true
edition.workspace    = true
description          = "Utilities to create GraphQL AST for biome_graphql_parser"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_graphql_syntax = { workspace = true }
biome_rowan          = { workspace = true }

[lints]
workspace = true
