[package]
name                 = "biome_rowan"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "Biome's custom Rowan definition"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[[bench]]
harness = false
name    = "mutation"

[dependencies]
biome_text_edit = { workspace = true }
biome_text_size = { workspace = true }
countme         = { workspace = true, optional = true }
hashbrown       = { workspace = true, features = ["inline-more", "raw-entry"] }
rustc-hash      = { workspace = true }
schemars        = { workspace = true, optional = true }
serde           = { workspace = true, optional = true }

[dev-dependencies]
iai               = "=0.1.1"
quickcheck        = { workspace = true }
quickcheck_macros = { workspace = true }
serde_json        = { workspace = true }

[features]
countme = ["dep:countme"]
schema  = ["dep:schemars", "serde"]
serde   = ["biome_text_size/serde", "biome_text_size/serde", "dep:serde"]

[lints]
workspace = true
