[package]
name                 = "biome_json_syntax"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "SyntaxKind and common rowan definitions for biome_json_parser"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_rowan       = { workspace = true, features = ["serde"] }
biome_string_case = { workspace = true }
camino            = { workspace = true }
directories       = { workspace = true }
schemars          = { workspace = true, optional = true }
serde             = { workspace = true, features = ["derive"] }

[features]
schema = ["biome_rowan/serde", "schemars"]

[lints]
workspace = true
