[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's tools to convert between LSP and Biome's data structures"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_lsp_converters"
publish              = true
repository.workspace = true
version              = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow           = { workspace = true }
biome_line_index = { workspace = true }
biome_text_size  = { workspace = true }
rustc-hash       = { workspace = true }
tower-lsp-server = { workspace = true }

[dev-dependencies]
tower = { workspace = true, features = ["timeout"] }

[lints]
workspace = true
