[package]
name                 = "biome_js_semantic"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "Biome's semantic model for JavaScript"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[dependencies]
biome_formatter = { workspace = true }
biome_js_syntax = { workspace = true }
biome_rowan     = { workspace = true }
rust-lapper     = { workspace = true }
rustc-hash      = { workspace = true }
smallvec        = { workspace = true }

[dev-dependencies]
biome_console     = { path = "../biome_console" }
biome_diagnostics = { path = "../biome_diagnostics" }
biome_js_parser   = { path = "../biome_js_parser" }

[lints]
workspace = true
