[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's semantic model for JavaScript"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_js_semantic"
repository.workspace = true
version              = "0.5.7"

[dependencies]
biome_js_syntax = { workspace = true }
biome_rowan     = { workspace = true }
rust-lapper     = "1.1.0"
rustc-hash      = { workspace = true }
smallvec        = { workspace = true }

[dev-dependencies]
biome_console     = { path = "../biome_console" }
biome_diagnostics = { path = "../biome_diagnostics" }
biome_js_parser   = { path = "../biome_js_parser" }

[lints]
workspace = true
