[package]
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
name                 = "rome_formatter_test"
repository.workspace = true
version              = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_console     = { workspace = true }
biome_diagnostics = { workspace = true }
biome_fs          = { workspace = true }
biome_parser      = { workspace = true }
biome_rowan       = { workspace = true }
insta             = { workspace = true, features = ["glob"] }
rome_formatter    = { workspace = true }
rome_service      = { workspace = true }
serde             = { version = "1", features = ["derive"] }
serde_json        = { workspace = true }
similar           = "2.1.0"
similar-asserts   = "1.2.0"

[dev-dependencies]
