[package]
edition = "2021"
name    = "xtask_libs_bench"
publish = false
version = "0.0.0"

[dependencies]
regex = { version = "1.6.0" }

[dev-dependencies]
criterion    = "0.4.0"
fastbloom-rs = "0.3.0"
fst          = "0.4.7"
iai          = "0.1.1"
memchr       = "2.5.0"
qp-trie      = "0.8.0"

[[bench]]
harness = false
name    = "contains_iai"

[[bench]]
harness = false
name    = "contains_criterion"

[[bin]]
bench = false
name  = "contains_iai"
path  = "bins/contains_iai.rs"
test  = false

[lints]
workspace = true
