[package]
edition = "2021"
name    = "xtask_libs_bench"
publish = false
version = "0.0.0"

[dependencies]
regex = { workspace = true }

[dev-dependencies]
criterion    = "0.5.1"
fastbloom-rs = "0.5.9"
fst          = "0.4.7"
iai          = "0.1.1"
memchr       = "2.7.4"
qp-trie      = "0.8.2"

[[bench]]
harness = false
name    = "contains_iai"

[[bench]]
harness = false
name    = "contains_criterion"

[[bin]]
bench = false
name  = "contains_iai"
path  = "bins/contains_iai.rs"
test  = false

[lints]
workspace = true
