[package]
authors.workspace    = true
categories.workspace = true
description          = "Utilities to edit text (This is taken from rust-analyzer)"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_text_edit"
repository.workspace = true
version              = "0.4.0"

[dependencies]
biome_text_size = { workspace = true, features = ["serde"] }
schemars        = { workspace = true, optional = true }
serde           = { workspace = true, features = ["derive"] }
similar         = { version = "2.1.0", features = ["unicode"] }

[features]
schemars = ["dep:schemars", "biome_text_size/schemars"]

[lints]
workspace = true
