[package]
authors.workspace    = true
categories           = ["development-tools"]
description          = "Rome's JSON formatter"
documentation        = "https://docs.rs/rome_js_formatter"
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "rome_json_formatter"
repository.workspace = true
version              = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_diagnostics = { workspace = true }
biome_formatter   = { workspace = true }
biome_json_syntax = { workspace = true }
biome_rowan       = { workspace = true }
biome_suppression = { workspace = true }

[dev-dependencies]
biome_formatter_test = { workspace = true }
biome_fs             = { workspace = true }
biome_json_factory   = { workspace = true }
biome_parser         = { workspace = true }
countme              = { workspace = true, features = ["enable"] }
insta                = { workspace = true, features = ["glob"] }
rome_json_parser     = { workspace = true }
serde                = { version = "1", features = ["derive"] }
serde_json           = { workspace = true }
tests_macros         = { workspace = true }

# cargo-workspaces metadata
[package.metadata.workspaces]
independent = true
