[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's parser shared infrastructure"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_parser"
repository.workspace = true
version              = "0.4.0"


[dependencies]
biome_console     = { workspace = true }
biome_diagnostics = { workspace = true }
biome_rowan       = { workspace = true }
bitflags          = { workspace = true }
drop_bomb         = "0.1.5"

[lints]
workspace = true
