[package]
name                 = "biome_parser"
version              = "0.5.7"
authors.workspace    = true
edition.workspace    = true
description          = "Biome's parser shared infrastructure"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[dependencies]
biome_console       = { workspace = true }
biome_diagnostics   = { workspace = true }
biome_rowan         = { workspace = true }
biome_unicode_table = { workspace = true }
drop_bomb           = "0.1.5"
enumflags2          = { workspace = true }
unicode-bom         = { workspace = true }

[lints]
workspace = true
