[package]
name                 = "biome_js_type_info"
version              = "0.0.1"
authors.workspace    = true
edition.workspace    = true
description          = "Data structures for tracking type information"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
publish              = true

[dependencies]
biome_formatter           = { workspace = true }
biome_js_syntax           = { workspace = true }
biome_js_type_info_macros = { workspace = true }
biome_resolver            = { workspace = true }
biome_rowan               = { workspace = true }
camino                    = { workspace = true }
hashbrown                 = { workspace = true }
paste                     = "1.0.15"
rustc-hash                = { workspace = true }

[dev-dependencies]
biome_js_formatter = { workspace = true }
biome_js_parser    = { workspace = true }
biome_test_utils   = { workspace = true }
insta              = { workspace = true }

[lints]
workspace = true
