# Analyzer benchmark, compares main and PR branch with Criterion.
# Comment with text containing `!bench_analyzer`, a new result will be commented at the bottom of this PR.

name: Analyzer Benchmark

on:
  issue_comment:
    types: [ created ]

env:
  RUST_LOG: info

jobs:
  bench:
    permissions:
      pull-requests: write
    name: Bench
    if: github.event.issue.pull_request && contains(github.event.comment.body, '!bench_analyzer')
    runs-on: ubuntu-latest

    steps:

      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.sha.outputs.result }}

      - name: Install toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Compile
        run: cargo codspeed build --features analyzer -p xtask_bench

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        timeout-minutes: 30
        with:
          run: cargo codspeed run analyzer
          token: ${{ secrets.CODSPEED_TOKEN }}
