name: Benchmarks

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths:
      - 'Cargo.lock'
      - 'crates/**_parser/**/*.rs'
      - 'crates/**_formatter/**/*.rs'
      - 'crates/**_analyze/**/*.rs'
  push:
    branches:
      - main
    paths:
      - 'Cargo.lock'
      - 'crates/**_parser/**/*.rs'
      - 'crates/**_formatter/**/*.rs'
      - 'crates/**_analyze/**/*.rs'

env:
  RUST_LOG: info

jobs:
  bench:
    permissions:
      pull-requests: write
    name: Bench
    runs-on: ubuntu-latest

    steps:

      - name: Checkout PR Branch
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ steps.sha.outputs.result }}

      - name: Install toolchain
        uses: moonrepo/setup-rust@d8048d4fdff0633123678b093726e6d7c8ad6de5 # v1.2.0
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed
          cache-base: main

      - name: Compile
        run: cargo codspeed build --features codspeed -p xtask_bench

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@0b631f8998f2389eb5144632b6f9f8fabd33a86e # v2.4.1
        timeout-minutes: 30
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
