name: JavaScript Parser Benchmark

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths:
      - 'crates/biome_js_parser/**'
      - 'crates/biome_parser/**'
  push:
    branches:
      - main
    paths:
      - 'crates/biome_js_parser/**'
      - 'crates/biome_parser/**'

env:
  RUST_LOG: info

jobs:
  bench:
    permissions:
      pull-requests: write
    name: Bench
    runs-on: ubuntu-latest

    steps:

      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.sha.outputs.result }}

      - name: Install toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Compile
        run: cargo codspeed build --feature codspeed js_parser -p xtask_bench

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        timeout-minutes: 30
        with:
          run: cargo codspeed run js_parser
          token: ${{ secrets.CODSPEED_TOKEN }}
