name: Lint rule docs
on:
  merge_group:
  pull_request:
    branches:
      - main
      - next
    paths:
      # Run only when we change the analyze crates
      - "**/biome_*_analyze/**/*.rs"
      - "**/biome_analyze/**/*.rs"
  push:
    branches:
      - main
      - next
    paths:
      # Run only when we change the analyze crates
      - "**/biome_*_analyze/**/*.rs"
      - "**/biome_analyze/**/*.rs"


# Cancel jobs when the PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1
  RUSTUP_WINDOWS_PATH_ADD_BIN: 1

jobs:
  rule_docs:
    name: Validate rules documentation
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Install toolchain
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1.2.2
        with:
          cache-base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run rules check
        run: cargo run -p rules_check
