name: Pull request Markdown
on:
  merge_group:
  pull_request:
    branches:
      - main
      - next
    paths:
      - "**/*.md"

jobs:
  lint:
    runs-on: depot-ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: DavidAnson/markdownlint-cli2-action@3575d252479e6880664c22c8d81ff0dc79ef5c22
        with:
          globs: |
            **/*.md
            #ROME_CHANGELOG.md
            #GOVERNANCE.md
            #**/node_modules
            #xtask/coverage
            #target
            #crates/biome_markdown_parser/tests
            #crates/biome_markdown_formatter/tests
            #crates/biome_js_formatter/report*.md
