name: Pull request Markdown
on:
  merge_group:
  pull_request:
    branches:
      - main
      - next
    paths:
      - "**/*.md"

jobs:
  lint:
    runs-on: depot-ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5
      - uses: DavidAnson/markdownlint-cli2-action@db7ea3f7fb64b40888e1a1bb732dbc804f305023
        with:
          globs: |
            **/*.md
            #ROME_CHANGELOG.md
            #GOVERNANCE.md
            #**/node_modules
            #xtask/coverage
            #target
            #crates/biome_markdown_parser/tests
            #crates/biome_js_formatter/report*.md
