name: Pull request Markdown
on:
  pull_request:
    branches:
      - main
      - next
    paths:
      - "**/*.md"

jobs:
  lint:
    runs-on: depot-ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: DavidAnson/markdownlint-cli2-action@451cad2cde7304d9c243aaaf2e894d74b428c4be
        with:
          globs: |
            **/*.md
            #ROME_CHANGELOG.md
            #GOVERNANCE.md
            #**/node_modules
            #xtask/coverage
            #target
            #crates/biome_markdown_parser/tests
            #crates/biome_js_formatter/report*.md
