# Jobs run on pull request in js folders
name: Pull request JS
on:
  merge_group:
  pull_request:
    branches:
      - main
    paths: # Only run when changes are made to js code
      - 'packages/@biomejs/**'
      - 'packages/aria-data/**'
      - 'packages/tailwindcss-config-analyzer/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

# Cancel jobs when the PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  format-js:
    name: Check JS Files
    runs-on: depot-ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Cache pnpm modules
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Run Biome CI check
        run: |
          pnpm i
          pnpm run ci
