# Jobs run on pull request in js folders
name: Pull request JS
on:
  pull_request:
    branches:
      - main
    paths: # Only run when changes are made to js code
      - 'packages/@biomejs/**'
      - 'packages/aria-data/**'
      - 'packages/tailwindcss-config-analyzer/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

# Cancel jobs when the PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  format-js:
    name: Check JS Files
    runs-on: depot-ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Cache pnpm modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Run Biome CI check
        run: |
          pnpm i
          pnpm run ci
