name: Pull request Markdown
on:
  merge_group:
  pull_request:
    branches:
      - main
      - next
    paths:
      - "**/*.md"

jobs:
  lint:
    runs-on: depot-ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: DavidAnson/markdownlint-cli2-action@36bf2f53fe58e6d4c086a1b420ee3f704d00cedc
        with:
          globs: |
            **/*.md
            #ROME_CHANGELOG.md
            #GOVERNANCE.md
            #**/node_modules
            #xtask/coverage
            #target
            #crates/biome_markdown_parser/tests
            #crates/biome_markdown_formatter/tests
            #crates/biome_js_formatter/report*.md
