name: Repository dispatch on main
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - next

permissions:
  contents: read
  actions: write

env:
  BIOME_WEBSITE_REPO: biomejs/website
  BIOME_PUSH_ON_MAIN_EVENT_TYPE: biome-push-on-main-event
  WASM_CACHE_KEY: wasm-cache

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wasm:
    name: Build @biomejs/wasm-web
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Warm up wasm cache
        id: cache-restore
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ./target
            ./packages/@biomejs/wasm-web
          key: ${{ env.WASM_CACHE_KEY }}

      - name: Install just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0

      - name: Install toolchain
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1.2.2
        with:
          bins: wasm-bindgen-cli@0.2.106, wasm-opt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build WASM module for the web
        run: just build-wasm-web

      # https://github.com/actions/cache/issues/342
      - name: Clear old wasm cache
        if: ${{ steps.cache-restore.outputs.cache-hit }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete ${{ env.WASM_CACHE_KEY }} --confirm
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true

      - name: Save new wasm cache
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ./target
            ./packages/@biomejs/wasm-web
          key: ${{ env.WASM_CACHE_KEY }}

      - name: Install pnpm
        # workaround for the issue https://github.com/actions/setup-node/issues/1222
        run: npm i -g --force corepack && corepack enable

      - name: Setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24.13.1
          cache: pnpm

      - name: Update package.json
        working-directory: packages/@biomejs/wasm-web
        run: |
          npm pkg set name='@biomejs/wasm-web'
          npm pkg set version='0.0.0-rev.${{ github.event.head_commit.id }}'

      - name: Verify WASM artifact exists
        working-directory: packages/@biomejs/wasm-web
        run: |
          test -f biome_wasm_bg.wasm && echo "Found wasm artifact biome_wasm_bg.wasm"

      - name: Publish
        working-directory: packages/@biomejs/wasm-web
        run: pnpx pkg-pr-new publish

  repository-dispatch:
    name: Repository dispatch
    needs: build-wasm
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Dispatch event on push
        if: ${{ github.event_name == 'push' }}
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.BIOME_REPOSITORY_DISPATCH }}
          repository: ${{ env.BIOME_WEBSITE_REPO }}
          event-type: ${{ env.BIOME_PUSH_ON_MAIN_EVENT_TYPE }}
          client-payload: '{"event": ${{ toJSON(github.event) }}}'
      # For testing only, the payload is mocked
      - name: Dispatch event on workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.BIOME_REPOSITORY_DISPATCH }}
          repository: ${{ env.BIOME_WEBSITE_REPO }}
          event-type: ${{ env.BIOME_PUSH_ON_MAIN_EVENT_TYPE }}
          client-payload: '{"event": {"head_commit": {"id": "${{ github.sha }}"}, "ref": "${{ github.ref }}"}}'
