# We have code that relies on Rust code AND JS code, we want to run this job when the relevant code changes
name: Checks for our runtimes
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'crates/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'crates/**'

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  apis-check:
    name: Checks on APIs project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
      - name: Free Disk Space
        uses: ./.github/actions/free-disk-space
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v3
      - name: Install toolchain
        uses: moonrepo/setup-rust@v1
      - name: Install libraries
        run: pnpm --filter @biomejs/js-api i
      - name: Compile backends
        run: |
          pnpm --filter @biomejs/js-api run build:wasm-bundler
          pnpm --filter @biomejs/js-api run build:wasm-node
          pnpm --filter @biomejs/js-api run build:wasm-web
          pnpm --filter @biomejs/backend-jsonrpc i
          pnpm --filter @biomejs/backend-jsonrpc run build
      - name: CI checks
        working-directory: packages/@biomejs/js-api
        run: pnpm run ci
