[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome's formatter test shared infrastructure"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_formatter_test"
publish              = false
repository.workspace = true
version              = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_configuration = { workspace = true }
biome_console       = { workspace = true }
biome_deserialize   = { workspace = true }
biome_diagnostics   = { workspace = true }
biome_formatter     = { workspace = true }
biome_fs            = { workspace = true }
biome_parser        = { workspace = true }
biome_rowan         = { workspace = true }
biome_service       = { workspace = true }
camino              = { workspace = true }
insta               = { workspace = true, features = ["glob"] }
serde               = { workspace = true, features = ["derive"] }
serde_json          = { workspace = true }
similar             = { workspace = true }
similar-asserts     = "1.6.1"

[dev-dependencies]

[lints]
workspace = true
